# This tells Hugo what the root path of the site is.
# This is automatically determined via the GitHub Action.
# For local development, a single / is usually desired.
baseURL = "/"

title           = "Bell AVR Documentation"
enableRobotsTXT = true
themesDir       = "node_modules"
theme           = "docsy"

# disable RSS feed
disableKinds = ["RSS"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# content directory settings
contentDir                     = "content/en"
defaultContentLanguage         = "en"
defaultContentLanguageInSubdir = false

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "monokai"

# Needed for some shortcodes
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
    unsafe = true

# Image processing configuration.
[imaging]
    resampleFilter = "CatmullRom"
    quality        = 75
    anchor         = "smart"

[outputs]
    home    = ["HTML", "print"]
    section = ["HTML", "print"]

[privacy.YouTube]
    PrivacyEnhanced = true

[params]
    copyright      = "Bell Flight"
    privacy_policy = "https://www.bellflight.com/legal/privacy-policy"

    # First one is picked as the Twitter card image if not set on page.
    # images = ["images/project-illustration.png"]

    # A link to latest version of the docs. Used in the "version-banner" partial to
    # point people to the main doc site.
    url_latest_version = "https://bellflight.github.io/AVR-2022"

    # Repository configuration (URLs for in-page links to opening issues and suggesting changes)
    github_repo = "https://github.com/bellflight/AVR-2022"
    # Discourse base URL
    discourse_forums          = "https://www.bellavrforum.org"
    # Discourse category to pre-assign to issues
    discourse_forums_category = "technical-support/documentation-feedback"

    # Specify a value here if your content directory is not in your repo's root directory
    # github_subdir = ""

    # Uncomment this if you have a newer GitHub repo with "main" as the default branch,
    # or specify a new value if you want to reference another branch in your GitHub links
    github_branch = "docs"

    # Enable Algolia DocSearch
    algolia_docsearch = false

    # Enable Lunr.js offline search
    offlineSearch = true

    # Enable syntax highlighting and copy buttons on code blocks with Prism
    prism_syntax_highlighting = false

# User interface configuration
[params.ui]
    # Set to true to disable breadcrumb navigation.
    breadcrumb_disable = false
    # Set to true to disable the About link in the site footer
    footer_about_disable = false
    # Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
    navbar_logo = true
    # Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
    navbar_translucent_over_cover_disable = false
    # Enable to show the side bar menu in its compact state.
    sidebar_menu_compact = true
    # Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
    sidebar_search_disable = false
    # Make the sidebar menu foldable
    sidebar_menu_foldable = true

[params.ui.feedback]
    enable = false

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
    enable = true

[params.links]
[[params.links.user]]
    name = "Bell Flight"
    url  = "https://www.bellflight.com"
    icon = "fa fa-helicopter"
    desc = "Welcome to the Future of Flight"

[[params.links.user]]
    name = "Careers"
    url  = "https://textron.taleo.net/careersection/bell/jobsearch.ftl?lang=en"
    icon = "fa fa-briefcase"

[[menu.main]]
    name   = "GitHub"
    weight = 50
    pre    = "<i class='fab fa-github'></i>"
    url    = "https://github.com/bellflight/AVR-2022/"

[[menu.main]]
    name   = "Forums"
    weight = 100
    pre    = "<i class='fa fa-users'></i>"
    url    = "https://bellavrforum.org/"
