version: "3"

services:
  mavp2p:
    image: ghcr.io/bellflight/vrc/2022/mavp2p:latest
    network_mode: host
    restart: unless-stopped
    devices:
      - /dev/ttyTHS1:/dev/ttyTHS1

  mqtt:
    image: ghcr.io/bellflight/vrc/2022/mqtt:latest
    ports:
      - "18830:18830"
    restart: on-failure

  status:
    depends_on:
      - mqtt
    image: ghcr.io/bellflight/vrc/2022/status:latest
    privileged: true
    restart: on-failure

  fcm:
    depends_on:
      - mqtt
      - mavp2p
    image: ghcr.io/bellflight/vrc/2022/fcm:latest
    network_mode: host
    restart: on-failure

  pcm:
    depends_on:
      - mqtt
    image: ghcr.io/bellflight/vrc/2022/pcm:latest
    restart: on-failure
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

  vio:
    depends_on:
      - mqtt
    image: ghcr.io/bellflight/vrc/2022/vio:latest
    privileged: true
    restart: on-failure
    volumes:
      - vio/settings:/usr/local/zed/settings/

  apriltag:
    depends_on:
      - mqtt
    build: apriltag
    restart: on-failure
    volumes:
      - /tmp/argus_socket:/tmp/argus_socket

  thermal:
    depends_on:
      - mqtt
    privileged: true
    image: ghcr.io/bellflight/vrc/2022/thermal:latest
    restart: on-failure

  fusion:
    depends_on:
      - mqtt
      - vio
    image: ghcr.io/bellflight/vrc/2022/fusion:latest
    restart: on-failure

  # sandbox:
  #   depends_on:
  #     - mqtt
  #   build: sandbox
  #   restart: on-failure
