name: Build Container Sandbox

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "VMC/sandbox/**"
  push:
    branches:
      - main
    paths:
      - "VMC/sandbox/**"

jobs:
  check:
    uses: ./.github/workflows/templates/container.yml
    with:
      image: "sandbox"