name: Build Container PCM

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "VMC/pcm/**"
      - "Libraries/**"
  push:
    branches:
      - main
    paths:
      - "VMC/pcm/**"
      - "Libraries/**"

jobs:
  check:
    uses: ./.github/workflows/templates/container.yml
    with:
      image: "pcm"