name: Build Container Simulator

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "VMC/simulator/**"
  push:
    branches:
      - main
    paths:
      - "VMC/simulator/**"

jobs:
  simulator:
    uses: ./.github/workflows/container.yml
    with:
      image: "fcm"