name: Build Containers

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "VMC/**"
  push:
    branches:
      - main
    paths:
      - "VMC/**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      matrix:
        # april tag module needs to be built on-device
        # sandbox should be built by students
        image: [fcm, fusion, mavp2p, mqtt, pcm, status, thermal, vio]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Copy Libraries
        run: python scripts/copy_libraries.py

      - name: Cache PX4
        if: matrix.image == 'fcm'
        uses: actions/cache@v3
        with:
          path: PX4/build
          key: px4-package-${{ hashFiles('PX4/patches/**') }}-${{ hashFiles('PX4/bell.xml') }}
          restore-keys: |
            px4-package-${{ hashFiles('PX4/patches/**') }}
            px4-package
            px4-firmware-${{ hashFiles('PX4/patches/**') }}
            px4-firmware

      - name: Generate Custom Pymavlink Package
        if: matrix.image == 'fcm'
        run: python3 PX4/generate.py host --pymavlink

      - name: Github CR Login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Container
        uses: docker/build-push-action@v2
        with:
          context: VMC/${{ matrix.image }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/bellflight/vrc/2022/${{ matrix.image }}:latest
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
