name: Python Checks VMC Thermal

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "VMC/thermal/**"
      - "Libraries/**"
      - "requirements-dev.txt"
      - "package-lock.json"

jobs:
  check:
    uses: ./.github/workflows/python_checks.yml
    with:
      project: "VMC/thermal"