name: Python Checks

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      cache:
        required: false
        type: boolean
        default: true

jobs:
  python-checks:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm

      - name: Setup Python (No Caching)
        if: inputs.cache == false
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Setup Python (Caching)
        if: inputs.cache == true
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache-dependency-path: ${{ inputs.project }}
          cache: pip

      - name: Install Packages
        run: |
          npm install
          python scripts/install_requirements.py --directory ${{ inputs.project }} --strict
          python scripts/copy_libraries.py

      - name: Check Formatting
        run: python scripts/step_summary.py
        env:
          RUN_CMD: python -m black ${{ inputs.project }} --verbose --check
          CMD_FAILURE_TEXT: |
            ## Formatting Failure :x:

            Run the following command locally and commit the changes:

            ```bash
            python -m black ${{ inputs.project }}
            ````

      - name: Check Import Order
        run: python scripts/step_summary.py
        env:
          RUN_CMD: python -m isort ${{ inputs.project }} --check
          CMD_FAILURE_TEXT: |
            ## Formatting Failure :x:

            Run the following command locally and commit the changes:

            ```bash
            python -m isort ${{ inputs.project }}
            ````

      - name: Check for Unused Imports
        run: python scripts/step_summary.py
        env:
          RUN_CMD: python -m autoflake --recursive ${{ inputs.project }} --check
          CMD_FAILURE_TEXT: |
            ## Unused Import(s) Detected :x:

            Run the following command locally and commit the changes:

            ```bash
            python -m autoflake --recursive --in-place --remove-all-unused-imports ${{ inputs.project }}
            ````

      - name: Check Type Hints
        run: python -m pyleft ${{ inputs.project }} --verbose

      - name: Check Typing
        run: npx pyright ${{ inputs.project }} --verbose

      - name: Linting
        run: python -m pflake8 ${{ inputs.project }}
